[project]
name = "fpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.21",
    "redis[hiredis]>=7.1.0",
    "websocket>=0.2.1",
]
